config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  mount Sidekiq::Web => '/sidekiq'

  resources :users

  root 'admin/dashboard#index'

  devise_for :user,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }

  scope module: 'admin', path: 'admin', as: 'admin' do
    get    '/dashboard/empresas',            to: 'dashboard/companies#list'
    get    '/dashboard/empresas/novo',       to: 'dashboard/companies#new'
    get    '/dashboard/empresas/:id/editar', to: 'dashboard/companies#edit', as: 'editar_empresa'
    post   '/dashboard/empresas/create',     to: 'dashboard/companies#create'
    put    '/dashboard/empresas/update',     to: 'dashboard/companies#update'
    delete '/dashboard/empresas/:id/delete', to: 'dashboard/companies#delete', as: 'deletar_empresa'

    get    '/dashboard/categorias',            to: 'dashboard/categories#list'
    get    '/dashboard/categorias/novo',       to: 'dashboard/categories#new'
    get    '/dashboard/categorias/:id/editar', to: 'dashboard/categories#edit', as: 'editar_categoria'
    post   '/dashboard/categorias/create',     to: 'dashboard/categories#create'
    put    '/dashboard/categorias/update',     to: 'dashboard/categories#update'
    delete '/dashboard/categorias/:id/delete', to: 'dashboard/categories#delete', as: 'deletar_categoria'

    get    '/dashboard/notas_fiscais',            to: 'dashboard/invoices#list'
    get    '/dashboard/notas_fiscais/novo',       to: 'dashboard/invoices#new'
    get    '/dashboard/notas_fiscais/:id/editar', to: 'dashboard/invoices#edit', as: 'editar_nota_fiscal'
    post   '/dashboard/notas_fiscais/create',     to: 'dashboard/invoices#create'
    put    '/dashboard/notas_fiscais/update',     to: 'dashboard/invoices#update'
    delete '/dashboard/notas_fiscais/:id/delete', to: 'dashboard/invoices#delete', as: 'deletar_nota_fiscal'

    get    '/dashboard/despesas',            to: 'dashboard/expenditures#list'
    get    '/dashboard/despesas/novo',       to: 'dashboard/expenditures#new'
    get    '/dashboard/despesas/:id/editar', to: 'dashboard/expenditures#edit', as: 'editar_despesas'
    post   '/dashboard/despesas/create',     to: 'dashboard/expenditures#create'
    put    '/dashboard/despesas/update',     to: 'dashboard/expenditures#update'
    delete '/dashboard/despesas/:id/delete', to: 'dashboard/expenditures#delete', as: 'deletar_despesas'

    get 'dashboard/historico_de_lancamentos', to: 'dashboard/release_histories#list', as: 'historico_de_lancamentos'

    get '/dashboard/limite_faturamento',        to: 'dashboard/invoicing_limits#index'
    put '/dashboard/limite_faturamento/update', to: 'dashboard/invoicing_limits#update'

    get '/dashboard/notificacoes/:id/editar',  to: 'dashboard/notifications#edit', as: 'editar_notificacoes'
    put '/dashboard/notificacoes/update_auth', to: 'dashboard/notifications#update_auth'
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name,
            :description,
            presence: { message: Messages.errors[:required_field] }

  enum status: Statuses::CATEGORIES

  has_many :expenditures

  PER_PAGE = 15

  scope :sorted_by_name, -> { order(:name) }
  scope :activated_names_list, -> { sorted_by_name.activated.pluck(:name, :id) }

  def activated?
    status == 'activated'
  end
end

app/controllers/admin/dashboard/categories_controller.rb
# frozen_string_literal: true

module Admin
  module Dashboard
    # class responbible by manage categories
    class CategoriesController < DashboardController
      before_action :find_category, only: %i[edit update delete]

      def new; end
      def edit; end

      def list
        @categories = Category
                      .sorted_by_name
                      .paginate(page: params[:page], per_page: Category::PER_PAGE)
      end

      def delete
        delete_obj(@category, admin_dashboard_categorias_path)
      end

      def update
        update_obj(@category, category_params, admin_dashboard_categorias_path)
      end

      def create
        create_obj(Category, category_params, admin_dashboard_categorias_path)
      end

      private

      def find_category
        @category = Category.find(params['id'] || params['category']['id'])
      end

      def category_params
        params
          .require(:category)
          .permit(:name, :description, :status)
      end
    end
  end
end

app/controllers/admin/dashboard/companies_controller.rb
# frozen_string_literal: true

module Admin
  module Dashboard
    # class responbible by manage companies
    class CompaniesController < DashboardController
      before_action :find_company, only: %i[edit delete update]

      def new; end
      def edit; end

      def list
        @companies = Company
                     .sorted_by_name
                     .paginate(page: params[:page], per_page: Company::PER_PAGE)
      end

      def update
        update_obj(@company, company_params, admin_dashboard_empresas_path)
      end

      def delete
        delete_obj(@company, admin_dashboard_empresas_path)
      end

      def create
        create_obj(Company, company_params, admin_dashboard_empresas_path)
      end

      private

      def find_company
        @company = Company.find(params['id'] || params['company']['id'])
      end

      def company_params
        params
          .require(:company)
          .permit(:name, :corporate_name, :cnpj, :status)
      end
    end
  end
end

app/controllers/admin/dashboard/expenditures_controller.rb
# frozen_string_literal: true

module Admin
  module Dashboard
    # class responbible by manage expenditures
    class ExpendituresController < DashboardController
      before_action :find_expenditure, only: %i[edit update delete]

      def new; end
      def edit; end

      def list
        @expenditures = Expenditure
                        .sorted_by_name
                        .paginate(page: params[:page], per_page: Expenditure::PER_PAGE)
      end

      def delete
        delete_obj(@expenditure, admin_dashboard_despesas_path)
      end

      def update
        update_obj(@expenditure, expenditure_params, admin_dashboard_despesas_path)
      end

      def create
        create_obj(Expenditure, expenditure_params, admin_dashboard_despesas_path)
      end

      def company
        Company.find_by_id(params['expenditure']['company'])
      end

      def category
        Category.find_by_id(params['expenditure']['category'])
      end

      private

      def find_expenditure
        @expenditure = Expenditure.find(params['id'] || params['expenditure']['id'])
      end

      def expenditure_params
        params
          .require(:expenditure)
          .permit(:name, :payment_date, :competence_date)
          .merge!({ 'company' => company,
                    'category' => category,
                    'amount' => params['expenditure']['amount'].to_currency })
      end
    end
  end
end

app/controllers/admin/dashboard/invoices_controller.rb
# frozen_string_literal: true

module Admin
  module Dashboard
    # class responbible by manage invoices
    class InvoicesController < DashboardController
      before_action :find_invoice, only: %i[edit delete update]

      def new; end
      def edit; end

      def list
        @invoices = Invoice
                    .all
                    .paginate(page: params[:page], per_page: Invoice::PER_PAGE)
      end

      def update
        update_obj(@invoice, invoice_params, admin_dashboard_notas_fiscais_path)
      end

      def create
        create_obj(Invoice, invoice_params, admin_dashboard_notas_fiscais_path)
      end

      def delete
        delete_obj(@invoice, admin_dashboard_notas_fiscais_path)
      end

      private

      def find_invoice
        @invoice = Invoice.find(params['id'] || params['invoice']['id'])
      end

      def company
        Company.find_by_id(params['invoice']['company'])
      end

      def invoice_params
        params
          .require(:invoice)
          .permit(:number, :description, :competence_month, :receipt_date)
          .merge!({ 'company' => company, 'amount' => params['invoice']['amount'].to_currency })
      end
    end
  end
end

app/controllers/admin/dashboard/invoicing_limits_controller.rb
# frozen_string_literal: true

module Admin
  module Dashboard
    # class responbible by manage invoicing limit
    class InvoicingLimitsController < DashboardController
      def index
        @invoicing = Invoicing.last.maximum_limit
      end

      def update
        invoicing = Invoicing.last
        invoicing.update!(invoicing_params)

        redirect_to admin_dashboard_limite_faturamento_path,
                    notice: t('messages.successes.updated_successfully')
      rescue StandardError => error
        Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

        redirect_to admin_dashboard_limite_faturamento_path,
                    alert: t('messages.errors.update_failed')
      end

      private

      def invoicing_params
        params
          .require(:invoicing_limit)
          .permit(:maximum_limit)
          .merge!({ 'maximum_limit' => params['invoicing_limit']['maximum_limit'].to_currency })
      end
    end
  end
end

app/controllers/admin/dashboard/notifications_controller.rb
# frozen_string_literal: true

module Admin
  module Dashboard
    # class responbible by manage user notifications
    class NotificationsController < DashboardController
      before_action :user, only: %i[edit update_auth]

      def edit; end

      def update_auth
        notification.update!(notification_params)

        redirect_to admin_editar_notificacoes_path(@user.id),
                    notice: t('messages.successes.updated_successfully')
      rescue StandardError => error
        Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

        redirect_to admin_editar_notificacoes_path(@user.id),
                    alert: t('messages.errors.update_failed')
      end

      private

      def user
        @user ||= User.find_by_email(current_user.email)
      end

      def notification
        @user.notification
      end

      def notification_params
        params
          .require(:notification)
          .permit(:email, :sms)
      end
    end
  end
end

app/controllers/admin/dashboard/release_histories_controller.rb
# frozen_string_literal: true

module Admin
  module Dashboard
    # class responbible by manage release histories
    class ReleaseHistoriesController < DashboardController
      def list
        @releases = ReleaseHistory.new(year: params['year']).call
      end
    end
  end
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

module Admin
  # class responbible by manage admin dashboard
  class DashboardController < ApplicationController
    before_action :authenticate_user!

    def index; end

    private

    def delete_obj(obj, route)
      obj.delete

      redirect_to route, notice: t('messages.successes.removed_successfully')
    rescue StandardError => error
      Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

      redirect_to route, alert: t('messages.errors.remove_failed')
    end

    def update_obj(obj, obj_params, route)
      obj.update!(obj_params)

      redirect_to route, notice: t('messages.successes.updated_successfully')
    rescue StandardError => error
      Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

      redirect_to route, alert: t('messages.errors.update_failed')
    end

    def create_obj(obj, obj_params, route)
      new_obj = obj.new(obj_params)
      new_obj.validate!
      new_obj.save!

      redirect_to route, notice: t('messages.successes.created_successfully')
    rescue StandardError => error
      Rails.logger.error("Message: #{error.message} - Backtrace: #{error.backtrace}")

      redirect_to route, alert: t('messages.errors.create_failed')
    end
  end
end

app/views/admin/dashboard/categories/edit.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to t('breadcrump.categories'), admin_dashboard_categorias_path, class: 'breadcrumb-item' %></li>
      <li class="breadcrumb-item active" aria-current="page"><%= t('breadcrump.edit_category') %></li>
    </ol>
  </nav>
  <%= render '././partials/messages' %>
  <h1 class="display-6"><%= t('.title', name: @category.name) %></h1>
  <hr>
  <div class='col-lg-6 offset-lg-3 col-md-6 offset-md-3 col-sm-6 offset-sm-3 col-xs-12'>
    <div class="card shadow-lg border-0 rounded-lg mt-4">
      <div class="card-body">
        <i><%= t('.required_fields') %></i>
        <br><br>
        <%= form_with scope: 'category', url: admin_dashboard_categorias_update_path, method: :put do |form| %>
          <%= form.label :name, t('.name'), class: 'form-label' %>
          <%= form.text_field :name,
                              class: 'form-control',
                              required: true %>
          <br>
          <%= form.label :description, t('.description'), class: 'form-label' %>
          <%= form.text_area :description,
                             class: 'form-control',
                             required: true %>
          <br>
          <%= form.label :status, t('.status'), class: 'form-label' %>
          <%= form.select :status, Statuses.categories, {}, { class: 'form-control' } %>
          <br><br>
          <%= form.hidden_field :id %>
          <%= form.submit t('.update_data_btn'), class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/dashboard/categories/list.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page"><%= t('breadcrump.categories') %></li>
    </ol>
  </nav>
  <%= render '././partials/messages' %>
  <h1 class="display-6"><%= t('.title') %></h1>
  <hr>
  <div class='col-lg-10 offset-lg-1 col-md-10 offset-md-1 col-sm-10 offset-sm-1 col-xs-12'>
    <div class="card shadow-lg border-0 rounded-lg mt-4">
      <div class="card-body">
        <%= link_to t('.add_category_btn'), admin_dashboard_categorias_novo_path, class: 'btn btn-primary' %>
        <br><br>
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col"><%= t('.name') %></th>
              <th scope="col"><%= t('.description') %></th>
              <th scope="col"><%= t('.status') %></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
              <tr style="<%= highlight_line(category) %>">
                <th scope="row"><%= category.name %></th>
                <td><%= category.description %></td>
                <td><%= t("statuses.#{category.status}") %></td>
                <td>
                  <%= link_to admin_editar_categoria_path(category.id), class: 'actions-link', title: t('.edit_lnk') do %>
                    <i class="bi bi-pencil-square"></i>
                  <% end %>
                  <%= link_to admin_deletar_categoria_path(category.id), class: 'actions-link', title: t('.remove_lnk'), method: :delete do %>
                    <i class="bi bi-trash"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @categories, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </div>
    </div>
  </div>
</div>

app/views/admin/dashboard/categories/new.html.erb
<div class="container">
  <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><%= link_to t('breadcrump.categories'), admin_dashboard_categorias_path, class: 'breadcrumb-item' %></li>
      <li class="breadcrumb-item active" aria-current="page"><%= t('breadcrump.new_category') %></li>
    </ol>
  </nav>
  <%= render '././partials/messages' %>
  <h1 class="display-6"><%= t('.title') %></h1>
  <hr>
  <div class='col-lg-6 offset-lg-3 col-md-6 offset-md-3 col-sm-6 offset-sm-3 col-xs-12'>
    <div class="card shadow-lg border-0 rounded-lg mt-4">
      <div class="card-body">
        <i><%= t('.required_fields') %></i>
        <br><br>
        <%= form_with scope: 'category', url: admin_dashboard_categorias_create_path do |form| %>
          <%= form.label :name, t('.name'), class: 'form-label' %>
          <%= form.text_field :name,
                              class: 'form-control',
                              required: true %>
          <br>
          <%= form.label :description, t('.description'), class: 'form-label' %>
          <%= form.text_area :description,
                             class: 'form-control',
                             required: true %>
          <br>
          <%= form.label :status, t('.status'), class: 'form-label' %>
          <%= form.select :status, Statuses.categories, {}, { class: 'form-control' } %>
          <br><br>
          <%= form.submit t('.save_data_btn'), class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>